# NUMPY-NUMERICAL PYTHON LIBRARY

In [4]:
import numpy as np
#import numpy library

In [5]:
#array list 
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2#2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr1 = np.array([1,2,3,4])
arr1#1d


array([1, 2, 3, 4])

In [7]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2[0][0]

1

In [8]:
print(arr2.ndim)#dimension
print(arr2.shape)#row*column
print(arr2.data)#address
print(arr2.size)

print(type(arr2))

2
(2, 4)
8
<class 'numpy.ndarray'>


# lab1 RANDOM NO. GENERATOR USING NUMPY

In [9]:
from numpy import random
x = random.randint(1000,size=(3,3))
x

array([[707, 779, 915],
       [846, 895, 957],
       [472, 550, 516]])

In [10]:
y = random.rand(10)
y

array([0.86586006, 0.99132592, 0.34163899, 0.76189143, 0.10771467,
       0.24315942, 0.95655874, 0.68486718, 0.564334  , 0.62791621])

In [11]:
z = random.random((2,2))
z

array([[0.8792679 , 0.76547422],
       [0.32425637, 0.78587628]])

In [12]:
x = random.randint(10,size=(3,3))
random.seed(10)  #any argument is used as an input
x            #generates value one time and keep it constant

array([[2, 3, 0],
       [8, 7, 3],
       [4, 1, 5]])

# Numpy functions

In [13]:
#zeros matrix/arrays
zero = np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#ones matrix/arrays
one = np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#identity matrix
idt = np.eye(3)
idt

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#create a constant matrix
const = np.full((3,3),5)
const

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# ARRAY indexing and slicing

In [17]:
arr4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#a[0][0] a[0][1] a[0][2]
#a[1][0] a[1][1] a[1][2]
#a[2][0] a[2][1] a[2][2]


In [18]:
arr4[0][1]=6
arr4

array([[ 1,  6,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
#slicing
#arr[slicing of rows,slicing of columns]
#arr[st(1):end,st(0):end]
arr4[1: ,1:3] #[rows which we dont want,columns which we dont want]

array([[ 6,  7],
       [10, 11]])

In [20]:
const2 = np.full((3,4),2)
const2

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

# array broadcasting

In [21]:
print(const2)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [22]:
print(arr4)

[[ 1  6  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
print(const2+arr4)

[[ 3  8  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [24]:
print(np.add(const2,arr4))

[[ 3  8  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [25]:
print(np.subtract(const2,arr4))

[[  1  -4  -1  -2]
 [ -3  -4  -5  -6]
 [ -7  -8  -9 -10]]


In [26]:
print(const2-arr4)

[[  1  -4  -1  -2]
 [ -3  -4  -5  -6]
 [ -7  -8  -9 -10]]


In [27]:
print(const2*arr4)

[[ 2 12  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [28]:
print(np.multiply(const2,arr4))

[[ 2 12  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [29]:
#square root of each element
np.sqrt(const2)

array([[1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356]])

In [30]:
np.sum(const2) #sum of all elements

24

In [31]:
np.sum(const2, axis=0) #sum of all column elements

array([6, 6, 6, 6])

In [32]:
np.sum(const2, axis=1)

array([8, 8, 8])

# calculate BMI OF players 

In [33]:
#height of players in inches
height_in = [61,62,65,70,72,75,74,63,66,68,69]
ht_np = np.array(height_in)
#convert into meters
ht_np = ht_np*0.0245
ht_np

array([1.4945, 1.519 , 1.5925, 1.715 , 1.764 , 1.8375, 1.813 , 1.5435,
       1.617 , 1.666 , 1.6905])

In [34]:
#weight of the players in pounds
weight_pd = [100,120,115,110,145,130,132,110,120,127,140]
wt_np = np.array(weight_pd)
#convert into kg
wt_np = wt_np*0.45
wt_np

array([45.  , 54.  , 51.75, 49.5 , 65.25, 58.5 , 59.4 , 49.5 , 54.  ,
       57.15, 63.  ])

In [35]:
#bmi=wt/[(ht)square]
bmi = wt_np/ht_np**2
bmi

array([20.1474773 , 23.40335994, 20.40569881, 16.82972231, 20.96927206,
       17.32611412, 18.07135997, 20.77743495, 20.65255179, 20.59046908,
       22.04500488])

In [36]:
bmi[bmi<20]

array([16.82972231, 17.32611412, 18.07135997])

In [37]:
bmi[bmi>21]

array([23.40335994, 22.04500488])

In [38]:
players = np.array([wt_np,ht_np])
players

array([[45.    , 54.    , 51.75  , 49.5   , 65.25  , 58.5   , 59.4   ,
        49.5   , 54.    , 57.15  , 63.    ],
       [ 1.4945,  1.519 ,  1.5925,  1.715 ,  1.764 ,  1.8375,  1.813 ,
         1.5435,  1.617 ,  1.666 ,  1.6905]])

In [39]:
players.shape

(2, 11)

 pt = players.T
pt

In [41]:
pt.shape

(11, 2)

# statastical operation

In [42]:
#min,max,mean,median,std,var,coorcoef,perc


In [46]:
print(np.amax(ht_np))
print(np.amin(ht_np))
print(np.corrcoef(ht_np,wt_np))#correlation coefficient

1.8375000000000001
1.4945000000000002
[[1.         0.69705141]
 [0.69705141 1.        ]]


# boolean

In [50]:
bools = [False,True,True,False,False]
bools
b = np.array(bools)

[False, True, True, False, False]

In [51]:
b.sum()

2

In [52]:
b.any()

True

In [54]:
b.all()

False

In [56]:
n = np.array(['b','b','b','c','c'])
n

array(['b', 'b', 'b', 'c', 'c'], dtype='<U1')

In [57]:
np.unique(n)

array(['b', 'c'], dtype='<U1')